# Generated by Django 4.2.6 on 2023-10-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capital', models.CharField(max_length=255)),
                ('people', models.IntegerField(null=True)),
                ('area', models.IntegerField(null=True)),
            ],
        ),
    ]
